"""Generate .obj meshes of Bruker's etched-silicon pyramid probes.

All three share one tip geometry — a 4-sided pyramid, front 15°, back 25°,
side 17.5° — and differ in apex radius, tip height and cantilever:

    RTESPA-150      8 nm apex (max 12), 10-15 µm tall, k 5 N/m,   f0 150 kHz
    RTESPA-300      the same tip,                      k 40 N/m,  f0 300 kHz
    ScanAsyst-Air   2 nm apex (max 12), 2.5-8 µm tall, k 0.4 N/m, f0 70 kHz

RTESPA-150 and -300 differ only in the lever, so one mesh serves both.

The apex is rounded as the morphological opening of the pyramid by a ball of
that radius (see make_snl10_obj.py): max(pyramid, sphere) never rounds
anything. The builders come from that script, driven at these angles.

Units are NANOMETRES, +Y up, apex at the origin, +Z the sharp front face.

Run:  python3 make_bruker_pyramid_obj.py
"""
import make_snl10_obj as snl

FRONT, BACK, SIDE = 15.0, 25.0, 17.5

PROBES = [
    ("rtespa", 8.0, 12_000.0,
     "Bruker RTESPA-150 and RTESPA-300 (same tip; levers differ: 5 vs 40 N/m).",
     "8 nm apex radius (datasheet nominal, max 12), tip height 10-15 um."),
    ("scanasyst_air", 2.0, 5_000.0,
     "Bruker ScanAsyst-Air (Si3N4, k 0.4 N/m, f0 70 kHz).",
     "2 nm apex radius (datasheet nominal, max 12), tip height 2.5-8.0 um."),
]


def main():
    snl.set_angles(FRONT, BACK, SIDE)
    for name, R, height, who, spec in PROBES:
        for suffix, h, note in [
            ("probe", height, "Whole tip, height %.0f nm." % height),
            ("apex", 100.0, "First 100 nm above the apex, where the rounding is resolvable."),
        ]:
            verts, faces, rim, apex_xz = snl.build(h, R)
            out = "%s_%s.obj" % (name, suffix)
            snl.write_obj(out, [
                who, note, spec,
                "Half-angles from vertical: front (+Z) %.1f deg, back (-Z) %.1f deg, side (+/-X) %.1f deg."
                % (FRONT, BACK, SIDE),
                "Apex rounded as the opening of the pyramid by a %.0f nm ball, which also" % R,
                "fillets the four edges. Units: nanometres, +Y up, apex at the origin.",
                "Generated by make_bruker_pyramid_obj.py",
            ], verts, faces)
            print("%-26s %6d verts %7d tris   height %7.0f nm   apex offset z %+.2f nm"
                  % (out, len(verts), len(faces), h, apex_xz[1]))


if __name__ == "__main__":
    main()
