"""Generate Wavefront .obj meshes of the BudgetSensors CS-20NG nanogrid.

CS-20NG (https://www.budgetsensors.com/xyz-calibration-nanogrid-cs-20ng) is
silicon dioxide structures on a 5 x 5 mm silicon chip with a ~20 nm step height
(the exact value is printed on each box). It carries three areas:

    1 x 1 mm         square pillars and holes, 10 µm pitch
    500 x 500 µm     circular pillars and holes plus X/Y lines, 5 µm pitch
    100 x 100 µm     circular holes, 500 nm pitch   <- the nanogrid

The builders are the ones written for the TGXYZ02 grating, driven at CS-20NG's
pitches and step height; hole diameters are taken at half the pitch, since
BudgetSensors publishes pitch and step but not feature width.

Units are NANOMETRES, +Y up, lower surface at y = 0, closed solids on a 1 µm
support slab — the same conventions as the other meshes here.

Run:  python3 make_cs20ng_obj.py
"""
import make_tgxyz02_obj as tg

STEP = 20.0          # nm, datasheet ("~20 nm")


def emit(name, builder, note):
    m, cells, cell = builder()
    m.write(name, [
        "BudgetSensors CS-20NG XYZ calibration nanogrid (SiO2 on Si).",
        note,
        "Step height %.0f nm (datasheet: ~20 nm, exact value on the box label)." % STEP,
        "Hole/pillar width taken at half the pitch (not published by the vendor).",
        "Lower surface at y = 0, %.0f um support slab below. Units: nanometres, +Y up." % (tg.BASE / 1000),
        "Generated by make_cs20ng_obj.py",
    ])
    print("%-30s %5d verts %6d tris   %d x %d cells of %.2f um"
          % (name, len(m.verts), len(m.faces), cells, cells, cell / 1000))


def main():
    tg.STEP = STEP

    tg.SPAN, tg.SQ_PITCH, tg.SQ_SIDE = 20_000.0, 10_000.0, 5_000.0
    emit("cs20ng_squares_20um.obj", tg.squares,
         "1 x 1 mm area: square pillars 5 um on a side, 10 um pitch, over 20 x 20 um.")

    tg.SPAN, tg.CIRC_PITCH, tg.CIRC_DIA = 20_000.0, 5_000.0, 2_500.0
    emit("cs20ng_circles_20um.obj", tg.circles,
         "500 x 500 um area: circular holes 2.5 um across, 5 um pitch, over 20 x 20 um.")

    tg.SPAN, tg.CIRC_PITCH, tg.CIRC_DIA = 2_000.0, 500.0, 250.0
    emit("cs20ng_nanogrid_2um.obj", tg.circles,
         "100 x 100 um nanogrid: circular holes 250 nm across, 500 nm pitch, over 2 x 2 um.")


if __name__ == "__main__":
    main()
